### ISSUE TITLE
試著把 source code 透過plugin打包，但是不要包到用不到 node_modules/

### ISSUE THREAD

**Issue by TCFeng** [chnbohwr/WiTodo#18]
1. 比較serverless-plugin-include-dependencies & Serverless Optimize Plugin

**Comment by TCFeng** [comment]
目前打包測試結果

1. 使用serverless-plugin-include-dependencies
    自己寫的src還是會全部包進去，不過會排除掉該function沒有用的node_module
    因此若有N隻function的內容沒有import任何node_module
    就會發現這幾隻的zip大小是一樣的。
    若有使用，則會依照該function有使用的node_module各自進行打包。
2. 使用serverless-plugin-optimize
    只會包含該function，不過目前測試是會把src+node_module全部綁到同一js中。
    這個要在研究一下參數有沒有辦法調整。
    另外打包的時間非常久。

**Comment by chnbohwr** [comment]
提問： `serverless-plugin-include-dependencies` 可以 exclude 掉 `aws-sdk` 嗎？

**Comment by TCFeng** [comment]
目前效能測試結果，使用postman，有多塞了一些用不到的Module
1. 不處理：
     全部包成同一包的情況下，只有一個package，並且把所有node_module一起包進去。
     總zip大小：87.7Mb
     啟動時間(ms) :  6062    隔8小時後重新呼叫 : 13359 
     呼叫9次時間：820, 763, 733, 802, 759, 720, 713, 806, 782

2.  使用serverless-plugin-include-dependencies
     總zip大小：342 KB
     啟動時間(ms) :  1553
     呼叫9次時間：811, 699, 892, 731, 736, 744, 718, 676, 936

3. 使用serverless-plugin-optimize
    總zip大小：139 KB
    啟動時間(ms) :  1682
    呼叫9次時間：770, 835, 794, 730, 728, 731, 769, 953, 926

**Comment by chnbohwr** [comment]
與 F 討論過 目前暫定使用 `serverless-plugin-include-dependencies`
