### ISSUE TITLE
Survey SQL lib for nodeJS

### ISSUE THREAD

**Issue by TCFeng** [chnbohwr/WiTodo#20]

**Comment by chnbohwr** [comment]
目前比較兩組 lib `pg`, `pg-promise`, 測驗內容為開啟 transition 然後 insert 10 筆資料

```
15:17 $ node index.js && node index2.js 
pg-promise insert 10 data: 4239.915ms
pg insert 10 data: 7445.347ms
```

程式上來說 `pg-promise` 比較簡單用

**Comment by vitaly-t** [comment]
See this: http://stackoverflow.com/questions/37300997/multi-row-insert-with-pg-promise

**Comment by chnbohwr** [comment]
done
