### ISSUE TITLE
study cli 設定 RDS, VPC

### ISSUE THREAD

**Issue by bbandydd** [chnbohwr/WiTodo#39]

**Comment by AmberChiu** [comment]
要创建 PostgreSQL 数据库实例，请执行以下操作，请结合以下参数使用 AWS CLI create-db-instance 命令：

--db-instance-identifier
--allocated-storage
--db-instance-class
--engine
--master-username
--master-user-password

http://docs.aws.amazon.com/zh_cn/AmazonRDS/latest/UserGuide/USER_CreatePostgreSQLInstance.html
http://docs.aws.amazon.com//cli/latest/reference/rds/create-db-instance.html

**Comment by AmberChiu** [comment]
https://www.cloudconformity.com/conformity-rules/RDS/instance-not-in-public-subnet.html

**Comment by AmberChiu** [comment]
aws rds create-db-instance 
--db-instance-identifier dbname 
--engine postgres 
--engine-version x.x.x 
--master-username xxx 
--master-user-password xxxxx
--db-instance-class xxxxx 
--no-multi-az 
--no-publicly-accessible 
--backup-retention-period 7 
--db-subnet-group-name default 
--vpc-security-group-ids sg-xxxx 
--allocated-storage 5
