### ISSUE TITLE
研究前端怎麼丟到 s3 上面有一個網址可以 access

### ISSUE THREAD

**Issue by chnbohwr** [chnbohwr/WiTodo#4]

**Comment by chnbohwr** [comment]
我有找到一個 serverless plugin 可以把前端的 dist 順便丟到 s3 上面，我放在 wiki 內
但是那是別人 FORK 出來的版本，所以要用這個指令安裝
```
npm install -S git://github.com/kevzettler/serverless-client-s3.git#serverless_1.0_beta_compatibility
```

**Comment by bbandydd** [comment]
http://witodo-web.s3-website-us-east-1.amazonaws.com/
目前還是有cross-domain問題

**Comment by bbandydd** [comment]
03/26  Hyman fixed cross-domain issue

**Comment by bbandydd** [comment]
using serverless-client-s3 version 1.0 beta

**Comment by bbandydd** [comment]
1. modify aws-cli to serverless-client-s3
2.fork serverless-client-s3 修改，可以自訂dist路徑

custom:
  client:
    path: /dist
    bucketName: witodo-web
