### ISSUE TITLE
制定 API

### ISSUE THREAD

**Issue by chnbohwr** [chnbohwr/WiTodo#5]

**Comment by AmberChiu** [comment]
API可以call了 @bbandydd 有問題再跟我說~
1. Create: https://ney73tbpg9.execute-api.us-east-1.amazonaws.com/dev/todoList/create
2. Update: https://ney73tbpg9.execute-api.us-east-1.amazonaws.com/dev/todoList/update
3. Delete: https://ney73tbpg9.execute-api.us-east-1.amazonaws.com/dev/todoList/delete
4. List: https://ney73tbpg9.execute-api.us-east-1.amazonaws.com/dev/todoList/list

**Comment by bbandydd** [comment]
Local call api會有cross-domain問題，
使用chrome plugin - Allow-Control-Allow-Origin

**Comment by bbandydd** [comment]
API Document
https://github.com/chnbohwr/WiTodo/wiki/API
